### ISSUE TITLE
Refactor?

### ISSUE THREAD

**Issue by jellythewobbly** [dchooyc/aoc#1]
`return right`
https://github.com/dchooyc/aoc/blob/7d794ce0c4becd3cef0f84c0a89e025422219cfe/2022/p8/solution.go#L151C1-L155C14

**Comment by jellythewobbly** [comment]
same for Python solution
https://github.com/dchooyc/aoc/blob/7d794ce0c4becd3cef0f84c0a89e025422219cfe/2022/p8/solver.py#L128-L131

**Comment by dchooyc** [comment]
It's written that way for my readability. So it's obvious that the true/ false of "right" is not the purpose of the entire function.

**Comment by dchooyc** [comment]
It's intentional
